overrides:
  '@eslint/plugin-kit@<0.3.4': '>=0.3.4'
  '@modelcontextprotocol/sdk@>=1.10.0 <=1.25.3': '>=1.26.0'
  '@remix-run/router@<=1.23.1': '>=1.23.2'
  nth-check@<2.0.1: '>=2.0.1'
  postcss@<8.4.31: '>=8.4.31'
  qs@<6.14.1: '>=6.14.1'
  webpack-dev-server@<=5.2.0: '>=5.2.1'
