overrides:
  '@eslint/plugin-kit@<0.3.4': '>=0.3.4'
  '@modelcontextprotocol/sdk@>=1.10.0 <=1.25.3': '>=1.26.0'
  '@remix-run/router@<=1.23.1': '>=1.23.2'
  ajv@<6.14.0: '>=6.14.0'
  ajv@>=7.0.0-alpha.0 <8.18.0: '>=8.18.0'
  hono@<4.11.10: '>=4.11.10'
  jsonpath@<1.2.0: '>=1.2.0'
  minimatch@<10.2.1: '>=10.2.1'
  nth-check@<2.0.1: '>=2.0.1'
  postcss@<8.4.31: '>=8.4.31'
  qs@<6.14.1: '>=6.14.1'
  qs@>=6.7.0 <=6.14.1: '>=6.14.2'
  webpack-dev-server@<=5.2.0: '>=5.2.1'
